### PR TITLE
Update bugbountytools.md

### PR DESCRIPTION
**Pull request by muhammadzeni**
Add naabu from projects discovery

## Related Issue

- Info about the related issue

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Code style update (formatting, local variables)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

## Screenshots(optional)

|      Original       |      Updated       |
| :-----------------: | :----------------: |
| original screenshot | updated screenshot |

### CODE REVIEW

**Comment by deephunt3r** [comment]
Hey @muhammadzeni thanks for your contributions. May I know that If your contributing for hacktoberfest?

**Comment by muhammadzeni** [comment]
> Hey @muhammadzeni thanks for your contributions. May I know that If your contributing for hacktoberfest?

Ya i contributed for hacktoberfest

**Comment by deephunt3r** [comment]
Hey @muhammadzeni thanks for contributing.

If your contributing for hacktoberfest then please do some better contributions

**Review by deephunt3r — APPROVED** [review]

**Comment by deephunt3r** [comment]
Hey @muhammadzeni thanks for contributing and don't forgot to ⭐ the repo :)

**Pull request merged**
