### PR TITLE
Update reports.md

### PR DESCRIPTION
**Pull request by SankalpaBaral**
I added a medium write-up link

### CODE REVIEW

**Comment by deephunt3r** [comment]
@SankalpaBaral  Hey, Thanks for making PR. Have you done it under Hacktoberfest?

**Comment by deephunt3r** [comment]
I got an idea instead of adding info about the reports like you did, why can't create a table which contains report heading, report link
If you want it for Hacktoberfest then I'll consider it :)
pls let me know

**Comment by SankalpaBaral** [comment]
Okay nice idea

**Comment by deephunt3r** [comment]
> Okay nice idea

So, can I close this PR now?

**Comment by muhammadzeni** [comment]
@deephunt3r haloo brother
Cannu help me / teaching me about hactoberfest coust i wass pr to you,but not you accep.
If its wrong / not good please tell me

**Pull request merged**
