### PR TITLE
Add dProg tool

### PR DESCRIPTION
**Pull request by xcapri**
I've just added dProg, and I have a little suggestion that it would be great if you added a brief info about the featured tools.

### CODE REVIEW

**Comment by deephunt3r** [comment]
@xcapri Hey, Thanks for making PR. Have you done it under Hacktoberfest?

**Comment by xcapri** [comment]
Alright, that's a great idea

**Comment by deephunt3r** [comment]
> Alright, that's a great idea

Can I close this PR then ?

**Comment by xcapri** [comment]
Yes u can close this, and then see https://github.com/deephunt3r/Bugbounty/pull/20

**Comment by deephunt3r** [comment]
Thanks :)

**Pull request closed without merging**
