### PR TITLE
desc:nmap

### PR DESCRIPTION
**Pull request by Taufik-H**

### CODE REVIEW

**Comment by deephunt3r** [comment]
Hey @Taufik-H can please add the description in English :)

**Comment by Taufik-H** [comment]
Sorry sir, I have changed the language to English

**Review by deephunt3r — APPROVED** [review]
If your contributing for hacktoberfest then please do much more worthy contributions

**Comment by deephunt3r** [comment]
If you found the repo helpful then star the repo :)

**Pull request merged**
